* Introduction

SeaMaster uses [Org mode](http://orgmode.org/) for its input files that
describe your setup, songs, and patches.. It is a text file with formatting
similar to Markdown. Only a few top-level sections are read by SeaMaster,
any others such as this one are ignored. They must be in the following
order, though ignored sections may appear between them.

- Instruments
- Messages
- Triggers
- Songs
- Set Lists

* Instruments

Short names for inputs and outputs don't have to be same or different. This
text is ignored.

- input MIDISPORT 4x4 Anniv Port A, kk, Kronos
- input MIDISPORT 4x4 Anniv Port B, ws, Wavestation
- output MIDISPORT 4x4 Anniv Port A, kk, Kronos
- output MIDISPORT 4x4 Anniv Port B, ws, Wavestation

* Messages

Bytes can be hex or decimal and can span multiple lines. Commas are ignored.
Sorry, no symbolic names yet.

** Tune Request

#+begin_example
  0xf6
#+end_example

* Triggers

Trigger actions are "next/prev(ious) song/patch" and "send message". "Send
message" requires a message name.

Commas are optional.

** next song
0xb0, 50, 127

** prev song
0xb0, 51, 127

** next patch
0xb0, 52, 127

** prev patch
0xb0, 53, 127

** send message Tune Request
0xb0, 54, 127

* Songs

Indentation doesn't matter. Again, this text is ignored. Song notes appear
after the song heading and before the first patch heading.

** To Each His Own

These are optional song notes.

*** Vanilla Through
**** kk, all, kk, all
**** ws, all, ws, all

** Kronos -> Wavestation

#+begin_example
Kronos channel 1 sent to Wavestation.

The begin/end example Org mode commands are ignored.
#+end_example

*** patch K to W
**** kk, all, ws, all
**** ws, all, kk, all

* Set Lists

** Tonight's Song List

- To Each His Own
- Kronos -> WaveStation
