* Introduction

SeaMaster uses [Org mode](http://orgmode.org/) for its input files that
describe your setup, songs, and patches.. It is a text file with formatting
similar to Markdown. Only a few top-level sections are read by SeaMaster,
any others such as this one are ignored. They must be in the following
order, though ignored sections may appear between them.

- Instruments
- Messages
- Triggers
- Songs
- Set Lists

* Instruments

Short names for inputs and outputs don't have to be same or different. This
text is ignored.

- input MIDISPORT 4x4 Anniv Port A, kk, Kronos
- input MIDISPORT 4x4 Anniv Port B, ws, Wavestation
- output MIDISPORT 4x4 Anniv Port A, kk, Kronos
- output MIDISPORT 4x4 Anniv Port B, ws, Wavestation

* Messages

Bytes can be hex or decimal and can span multiple lines. Commas are ignored.
Sorry, no symbolic names yet.

** Tune Request

#+begin_example
  0xf6
#+end_example

* Triggers

Triggers listen for a particular message from an input instrument and, when
that message is seen, perform some action.

Trigger actions are "next/prev(ious) song/patch" or "message". "Message"
requires a message name.

Trigger headers consist of a comma-separated list of an input short name, an
action name, and in the case of the "send message" action, the message name.

The message to listen for is in the body under the header. It consists of
one to three bytes separated by whitespace and optional commas. Each byte
may be expressed as decimal or "0xff"-style hex numbers (case is ignored).

Commas are optional.

  | input | bytes         | action     | message      |
  |-------+---------------+------------+--------------|
  | one   | 0xb0, 50, 127 | next song  |              |
  | one   | 0xb0, 51, 127 | prev song  |              |
  | one   | 0xb0, 52, 127 | next patch |              |
  | one   | 0xb0, 53, 127 | prev patch |              |
  | one   | 0xb0, 54, 127 | message    | Tune Request |

* Songs

Indentation doesn't matter. Again, this text is ignored. Song notes appear
after the song heading and before the first patch heading.

** To Each His Own

These are optional song notes.

*** Vanilla Through
**** kk, all, kk, all
**** ws, all, ws, all

** Kronos -> Wavestation

#+begin_example
Kronos channel 1 sent to Wavestation.

The begin/end example Org mode commands are ignored.
#+end_example

*** patch K to W
**** kk, all, ws, all
**** ws, all, kk, all

* Set Lists

** Tonight's Song List

- To Each His Own
- Kronos -> WaveStation
