* Introduction

This is an example [[https://github.com/jimm/seamaster][SeaMaster]] file. It is an [[http://orgmode.org/][Org mode]] file, which is a plain
text file format similar to Markdown. This file describes your MIDI setup,
songs, and patches. Only a few top-level sections are read by SeaMaster, any
others such as this one are ignored. They must be in the following order,
though ignored sections may appear anywhere, including between them.

- Instruments
- Messages (/optional/)
- Triggers (/optional/)
- Songs
  - Patches
    - Connections
- Set Lists (/optional/)

This sections, since it isn't one of those, is ignored.

In general, indentation doesn't matter. Beginning whitespace is ignored,
except within song notes.

* Instruments

This section describes the instruments in your MIDI setup by listing input
and output MIDI ports. Each one specifies the port name, a short name you
use below to refer to the port, and a longer display name.

The short names for inputs and outputs need to be unique within the type
(input or output), but an input and an output can share the same short and
long names.

The header row and separator rows are optional. The first few letters of the
first column determines if the row describes an input or output. If they
match "in" or "out" then the row describes a MIDI port.

All text except the table itself is ignored.

| I/O | port                       | name        |
|-----+----------------------------+-------------|
| in  | MIDISPORT 4x4 Anniv Port A | Kronos      |
| in  | MIDISPORT 4x4 Anniv Port B | Wavestation |
|-----+----------------------------+-------------|
| out | MIDISPORT 4x4 Anniv Port A | Kronos      |
| out | MIDISPORT 4x4 Anniv Port B | Wavestation |

* Messages

A message is a named list of MIDI one- to three-byte messages. Bytes can be
hex or decimal. There can be multiple messages but each one must appear on a
separate line. Sysex is not yet supported. Commas are ignored. Sorry, there
is not yet support for symbolic names such as "CONTROLLER" or "TUNE_REQUEST"
for bytes yet.

Within each message only Org mode block delimiters ("#+begin_" and "#_end_"
lines) are ignored; all other lines are assumed to be MIDI messages. That
means all of your message comments/notes need to be here, not inside the
messages' sections.

** Tune Request

#+begin_example
  0xf6
#+end_example

** Multiple Note-Offs

0x80, 64, 0
0x81, 64, 0
0x82, 42, 0

* Triggers

Triggers listen for a particular message from an input instrument and, when
that message is seen, perform some action.

The title and separator lines are ignored. Actually, any line where the
first column isn't a legal input instrument short name is ignored.

The first column contains the input instrument short name. The second is a
one- to three-byte MIDI message that triggers the action or message send.

The third column is one of "next song", "next patch", "prev (or 'previous')
song", "prev patch", or "message". "Message" requires a message name.


  | input       | bytes         | action     | message      |
  |-------------+---------------+------------+--------------|
  | Kronos      | 0xb0, 50, 127 | next song  |              |
  | Kronos      | 0xb0, 51, 127 | prev song  |              |
  | Kronos      | 0xb0, 52, 127 | next patch |              |
  | Kronos      | 0xb0, 53, 127 | prev patch |              |
  | Wavestation | 0xb0, 50, 127 | message    | Tune Request |

* Songs

Indentation doesn't matter. Again, this text is ignored. Song notes appear
after the song heading and before the first patch heading.

** My First Song

These are optional song notes.
They will be displayed on-screen.

*** Vanilla Through
**** Kronos, all, Kronos, all
**** Wavestation, all, Wavestation, all

** Kronos -> Wavestation

#+begin_example
Kronos channel 1 sent to Wavestation.

The Org mode block begin/end commands are ignored.
#+end_example

*** patch K to W
**** Kronos, all, Wavestation, all
**** Wavestation, all, Kronos, all

** Splits, Transposes, and Mappings

This patch creates a three-part split with some overlap.

The bottom part sends the Wavestation's channel 1 to the Kronos on channel
1, transposing all notes up two octaves. The key zone goes up to B2, and the
patch also filters out the sustain pedal.

The middle part goes from C3 - B4 and gets sent to channel 2.

The bottom part starts at C4 and gets sent to channel 3. It overlaps one
octave of the middle part.

*** Wavestation playing Kronos with everything

**** Wavestation, 1, Kronos, 1
     - prog 100
     - xpose 24
     - zone 0, b2
     - cc 64 filter

**** Wavestation, 1, Kronos, 2
     - prog 99
     - zone c3, b4

**** Wavestation, 1, Kronos, 3
     - prog 1
     - zone c4, 127
     - xpose -12

* Set Lists

The default bullet list character is "-". Two other bullet list characters
are accepted: "\*" and "+". Org mode requires that lists using "\*" are
indented, else they will be seen as top-level headlines.

** Tonight's Set List

- To Each His Own
- Kronos -> Wavestation

** Tomorrow's

   * Kronos -> Wavestation
   * To Each His Own
